services:
  roman-numeral-ui:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: roman-numeral-ui
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - ENV=PROD
      - DD_API_KEY=${DD_API_KEY:-}
      - DD_AGENT_HOST=datadog-agent
      - DD_SERVICE=roman-numeral-ui
      - DD_ENV=production
      - DD_VERSION=1.0.0
      - DD_LOGS_INJECTION=true
      - DD_RUNTIME_METRICS_ENABLED=true
      - DD_PROFILING_ENABLED=true
      - DD_TRACE_AGENT_PORT=8126
      - DD_DOGSTATSD_PORT=8125
      - LOG_LEVEL=info
    volumes:
      - roman-numeral-ui-logs:/var/log/roman-numeral-ui
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - roman-numeral-ui-network
    labels:
      - "com.datadoghq.ad.logs=[{\"source\": \"roman-numeral-ui\", \"service\": \"roman-numeral-ui\"}]"
    depends_on:
      - datadog-agent

  # DataDog Agent for monitoring
  datadog-agent:
    image: gcr.io/datadoghq/agent:7
    container_name: dd-agent-ui
    environment:
      - DD_API_KEY=${DD_API_KEY:-}
      - DD_SITE=us5.datadoghq.com
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_LOGS_ENABLED=true
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_COLLECT_KUBERNETES_EVENTS=false
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_CONTAINER_EXCLUDE="name:datadog-agent"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - roman-numeral-ui-logs:/var/log/roman-numeral-ui:ro
      - ./datadog.yaml:/etc/datadog-agent/datadog.yaml:ro
      - ./conf.d:/etc/datadog-agent/conf.d:ro
    ports:
      - "8127:8126"  # APM
      - "8128:8125/udp"  # StatsD
    restart: unless-stopped
    networks:
      - roman-numeral-ui-network

volumes:
  roman-numeral-ui-logs:
    driver: local

networks:
  roman-numeral-ui-network:
    driver: bridge 