/* tslint:disable */
/* eslint-disable */
/**
 * Roman Numeral API
 * API for Roman numeral conversions
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConvertIntegerToRomanNumeralResponse
 */
export interface ConvertIntegerToRomanNumeralResponse {
    /**
     * original input integer provided to convert 
     * @type {string}
     * @memberof ConvertIntegerToRomanNumeralResponse
     */
    input: string;
    /**
     * result 
     * @type {string}
     * @memberof ConvertIntegerToRomanNumeralResponse
     */
    output: string;
}

/**
 * Check if a given object implements the ConvertIntegerToRomanNumeralResponse interface.
 */
export function instanceOfConvertIntegerToRomanNumeralResponse(value: object): value is ConvertIntegerToRomanNumeralResponse {
    if (!('input' in value) || value['input'] === undefined) return false;
    if (!('output' in value) || value['output'] === undefined) return false;
    return true;
}

export function ConvertIntegerToRomanNumeralResponseFromJSON(json: any): ConvertIntegerToRomanNumeralResponse {
    return ConvertIntegerToRomanNumeralResponseFromJSONTyped(json, false);
}

export function ConvertIntegerToRomanNumeralResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConvertIntegerToRomanNumeralResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'input': json['input'],
        'output': json['output'],
    };
}

export function ConvertIntegerToRomanNumeralResponseToJSON(json: any): ConvertIntegerToRomanNumeralResponse {
    return ConvertIntegerToRomanNumeralResponseToJSONTyped(json, false);
}

export function ConvertIntegerToRomanNumeralResponseToJSONTyped(value?: ConvertIntegerToRomanNumeralResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'input': value['input'],
        'output': value['output'],
    };
}

