/* tslint:disable */
/* eslint-disable */
/**
 * Roman Numeral API
 * API for Roman numeral conversions
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Health200Response,
} from '../models/index';
import {
    Health200ResponseFromJSON,
    Health200ResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class HealthApi extends runtime.BaseAPI {

    /**
     * Health check endpoint
     */
    async healthRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Health200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/health`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Health200ResponseFromJSON(jsonValue));
    }

    /**
     * Health check endpoint
     */
    async health(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Health200Response> {
        const response = await this.healthRaw(initOverrides);
        return await response.value();
    }

}
