/* tslint:disable */
/* eslint-disable */
/**
 * Roman Numeral API
 * API for Roman numeral conversions
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ConvertIntegerToRomanNumeralResponse,
} from '../models/index';
import {
    ConvertIntegerToRomanNumeralResponseFromJSON,
    ConvertIntegerToRomanNumeralResponseToJSON,
} from '../models/index';

export interface ConvertIntegerToRomanNumeralRequest {
    query: number;
}

/**
 * 
 */
export class RomanNumeralApi extends runtime.BaseAPI {

    /**
     * Convert a number to a roman numeral
     */
    async convertIntegerToRomanNumeralRaw(requestParameters: ConvertIntegerToRomanNumeralRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConvertIntegerToRomanNumeralResponse>> {
        if (requestParameters['query'] == null) {
            throw new runtime.RequiredError(
                'query',
                'Required parameter "query" was null or undefined when calling convertIntegerToRomanNumeral().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/romannumeral`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConvertIntegerToRomanNumeralResponseFromJSON(jsonValue));
    }

    /**
     * Convert a number to a roman numeral
     */
    async convertIntegerToRomanNumeral(query: number, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConvertIntegerToRomanNumeralResponse> {
        const response = await this.convertIntegerToRomanNumeralRaw({ query: query }, initOverrides);
        return await response.value();
    }

}
